# docker-compose.yaml
services:
  fastapi_app:
    build: .
    image: madebayoresgitry.azurecr.io/fastapi_app:latest
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mssql+pyodbc://<admin>:<ussba2025RBX>@<madebayosqlserver>.database.windows.net:1433/<ussba_db>?driver=ODBC+Driver+17+for+SQL+Server&encrypt=yes&trustservercertificate=no"
      SECRET_KEY: "thequickbrownfoxjumpsoverthelazydog"
    restart: always

# services:
#   fastapi_app:
#     build: .
#     image: madebayoresgitry.azurecr.io/fastapi_app:latest
#     ports:
#       - "8000:8000"
#     environment:
#       POSTGRES_USER: demo_user
#       POSTGRES_PASSWORD: MyPassword
#       POSTGRES_DB: demo_db
#       POSTGRES_HOST: postgres_db
#       POSTGRES_PORT: 5432
#       POSTGRES_RDY: 1
#       SECRET_KEY: thequickbrownfoxjumpsoverthelazydog
#       DATABASE_URL: "mssql+pyodbc://<admin>:<ussba2025RBX>@<madebayosqlserver>.database.windows.net:1433/<ussba_db>?driver=ODBC+Driver+17+for+SQL+Server&encrypt=yes&trustservercertificate=no"
#     volumes:
#       - ./data:/app/data  # Example volume mapping for persistent data
#     restart: always
#     depends_on:
#       - db

#   db:
#     image: postgres:14
#     environment:
#       POSTGRES_USER: demo_user
#       POSTGRES_PASSWORD: MyPassword
#       POSTGRES_DB: demo_db
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     restart: always
#     platform: linux/amd64

# volumes:
#   postgres_data:  # Persistent storage for PostgreSQL data